# Generated by Django 4.2.7 on 2024-02-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user_type',
            field=models.CharField(default='Patient', editable=False, max_length=10),
        ),
    ]
