# Generated by Django 4.2.7 on 2024-02-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user_type',
            field=models.CharField(default='Doctor', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='doctors/images/default.jpg', upload_to='doctor/media/uploads/'),
        ),
    ]
