# Generated by Django 4.2.7 on 2024-02-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_user_type_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='doctor/media/uploads/default.jpg', upload_to='doctor/media/uploads/'),
        ),
    ]
