# Generated by Django 4.2.7 on 2024-02-29 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
    ]
