# Generated by Django 4.2.7 on 2024-03-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_review_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialization',
            new_name='Expertise',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='specialization',
            new_name='expertise',
        ),
    ]
